name:                servant-elm-street
version:             0.1.0.0
github:              "ChaosGroup//servant-elm-street"
license:             BSD3
author:              "Magdalena Lungolova"
maintainer:          "mvlungolova@gmail.com"
copyright:           "Copyright 2021 Chaos Software OOD"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/ChaosGroup/servant-elm-street/blob/main/README.md>

library:
  source-dirs: src

dependencies:
- servant-foreign
- text
- base >= 4.7 && < 5
- elm-street
- wai
- microlens
- prettyprinter

ghc-options:
- -Wall
- -Werror
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-deriving-strategies
- -Wmissing-export-lists
- -Wunused-packages

executables:
  servant-elm-street-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-elm-street

tests:
  servant-elm-street-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-elm-street
