name:                servant-elm-street
version:             0.1.0.0
github:              "ChaosGroup//servant-elm-street"
license:             BSD3
author:              "Magdalena Lungolova"
maintainer:          "mvlungolova@gmail.com"
copyright:           "Copyright 2022 Chaos Software OOD"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/ChaosGroup/servant-elm-street/blob/main/README.md>

dependencies:
- servant-foreign
- text
- base >= 4.7 && < 5
- elm-street
- microlens
- prettyprinter


library:
  source-dirs: src

ghc-options:
- -Werror
- -Wall
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-deriving-strategies
- -Wmissing-export-lists
- -Wunused-packages