name:                servant-elm-street
version:             0.1.0.0
github:              "githubuser/servant-elm-street"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-elm-street#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

dependencies:
- servant-foreign
- text
- servant-elm
- base >= 4.7 && < 5
- aeson
- casing
- elm-street
- filepath
- servant
- servant-server
- wai
- warp
- servant-js
- random
- elm-bridge
- wl-pprint-text

executables:
  servant-elm-street-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-elm-street
    - servant-foreign
    - servant
    - base
    - text
tests:
  servant-elm-street-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-elm-street
