name:                backend
version:             0.1.0.0
github:              "ChaosGroup//backend"
license:             BSD3
author:              "Magdalena Lungolova"
maintainer:          "mvlungolova@gmail.com"
copyright:           "Copyright 2022 Chaos Software OOD"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/backend#readme>

dependencies:
- base >= 4.7 && < 5
- elm-street

ghc-options:
- -Werror
- -Wall
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-export-lists
- -Wunused-packages

library:
  source-dirs: src
  dependencies:
  - servant-server
  - aeson
  - wai
  - text
  - bytestring

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
    - servant-elm-street
    - warp
    - wai-cors